### PR TITLE
Insert - Use Schema for Table Name

### PR DESCRIPTION
**Pull request by scrawfor**
Sorry for the dirty PR, but I wanted to make sure you were open to accepting them before cleaning it up.

This supports using a clickhouse database / kysley schema on insert tables.  Lines 47/48.

If you're interested let me know and I can cleanup the formatting issues.

### CODE REVIEW

**Comment by maktouch** [comment]
Yep ill accept it

**Comment by scrawfor** [comment]
> Yep ill accept it

Awesome.  I just cleaned it up.   Let me know if you want any tweaks.

Also, thanks for pulling this adapter together.  Very helpful!

**Review by maktouch — APPROVED** [review]

**Comment by maktouch** [comment]
Sorry for late reply! I'll merge today and make a release. Thanks for making the patch!

**Comment by scrawfor** [comment]
No problem!  Thanks for merging!

**Comment by scrawfor** [comment]
@maktouch - Any chance you could push out a release for this?  I've been using a manual git reference, but it would be nice to just use the version.


Thanks!

**Pull request merged**
